### ISSUE TITLE
BIOS设置求助

### ISSUE THREAD

**Issue by KiteMJ** [Yellowpal/ASRock-Z370M-ITX-AC-OpenCore#3]
大佬，可否分享下BIOS设置备份？设置了几次都无法启动

**Comment by Yellowpal** [comment]
> 

你有按这个设置？我印象中没有特殊的地方
https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#intel-bios-settings

**Comment by KiteMJ** [comment]
感谢，我再检查下设置。
